reference_genome:
  - file: 'data/{dir}/{lib}'
    opts: 'cfg/{dir}/reference.fa'

reference_annotation:
  - file: 'data/{dir}/{lib}'
    opts: 'cfg/{dir}/annotation.gff3.gz'

essential_genes:
  - file: 'data/{dir}/{lib}'
    opts: 'cfg/{dir}/essential.tab'

knockouts:
  - file: 'data/Simulation/{lib}'
    opts: 'cfg/Uhse_et_al.2018/knockouts.gff'
  - file: 'data/{dir}/{lib}'
    opts: 'cfg/{dir}/knockouts.gff'

trimmomatic:
  - file: '*'
    opts: 'ILLUMINACLIP:cfg/Uhse_et_al.2018.adapters.fa:2:24:15:1:true MINLEN:40'

cassette:
  - file: 'data/{dir}/{lib}'
    opts: 'cfg/{dir}/cassette.fa'

ngm:
  - file: '*'
    opts: '--end-to-end --pair-score-cutoff 0.5 --sensitivity 0.3 --kmer 13 --kmer-skip 0 --skip-save'

knockout_assignment:
  - file: '*'
    opts: '--mapping-fuzzyness 10 --max-fragment-length 1000'

trumicount:
#  - file: 'data/Uhse_et_al.2018/expB.r1-in.*'
#    opts: '--threshold 2'
#  - file: 'data/Uhse_et_al.2018/expB.r1-out.*'
#    opts: '--threshold 5'
#  - file: 'data/Uhse_et_al.2018/expB.r2-out.*'
#    opts: '--threshold 5'
#  - file: 'data/Uhse_et_al.2018/expB.r3-out.*'
#    opts: '--threshold 9'
#  - file: 'data/Transposon/r77647-*'
#    opts: '--threshold 2 --plot-hist-xmax 40 --plot-hist-bin 1 --umitools-option --edit-distance-threshold=2'
  - file: 'data/PiggyBac_2022/Input_vs_Sorbitol-*'
    opts: '--threshold 2 --plot-hist-xmax 40 --plot-hist-bin 1 --umitools-option --edit-distance-threshold=2'
